version: '3.9'
services:
  db:
    image: mongo:6.0.2
    ports:
      - 27017:27017
    command: mongod 
  api: 
    build:
      context: .
      args:
        # set this commandline arg based on the env variable where the compose file is run
        jwtPrivateKey: ${vidly_jwtPrivateKey}

    image: vidly-api
    ports:
      - 3000:3000
    depends_on: 
      - db
    environment:
      - NODE_ENV=prod
    command: npm run start
