version: '3.9'
services:
  db:
    image: mongo:6.0.2
    ports:
      - 27017:27017
    network_mode: bridge
    # spawn with replica set for Transactions
    command: mongod --bind_ip_all --replSet rs0